using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CountriesApp.Models;

namespace CountriesApp.Controllers
{
    public class CountriesController : Controller
    {
        private static int ActualIndex = 0;
        private static int PopulationIndex = 1;
        private CountriesEntities db = new CountriesEntities();

        #region Autogenerated Code
        // GET: Countries
        public ActionResult Index()
        {
            var countries = db.Countries.Include(c => c.Person);
            return View(countries.ToList());
        }

        // GET: Countries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // GET: Countries/Create
        public ActionResult Create()
        {
            ViewBag.presidentID = new SelectList(db.People, "id", "firstName");
            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,area,population,flag,anthem,presidentID")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Countries.Add(country);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.presidentID = new SelectList(db.People, "id", "firstName", country.presidentID);
            return View(country);
        }

        // GET: Countries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            ViewBag.presidentID = new SelectList(db.People, "id", "firstName", country.presidentID);
            return View(country);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,area,population,flag,anthem,presidentID")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Entry(country).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.presidentID = new SelectList(db.People, "id", "firstName", country.presidentID);
            return View(country);
        }

        // GET: Countries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Country country = db.Countries.Find(id);
            db.Countries.Remove(country);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion

        public ActionResult AllCountries()
        {
            ViewBag.ActualIndex = 0;
            ViewBag.PopulationIndex = 1;

            Country country = db.Countries.Include(c => c.Person).First();

            return View(country);
        }

        public ActionResult ChangeCountry(short actual, short i)
        {
            List<Country> countries = db.Countries.Include(c => c.Person).ToList();
            Country country;

            actual += i;
            actual = actual < 0 ? (short)(countries.Count - 1) : (short)(actual == countries.Count ? 0 : actual);

            ViewBag.ActualIndex = actual;
            ViewBag.PopulationIndex = 1;

            country = countries[actual];

            return View("AllCountries", country);
        }

        public ActionResult TravelPopulation(short actualCountry, short actualPopulation, short sum)
        {
            List<Country> countries = db.Countries.Include(c => c.Person).ToList();
            Country country;
            int actualPopulationIndex;

            ViewBag.ActualIndex = actualCountry;
            country = countries[actualCountry];

            actualPopulationIndex = actualPopulation + sum;

            if (actualPopulationIndex == 0)
                actualPopulationIndex = country.People1.Count() / 10 + 1;

            if (country.People1.Count() < (actualPopulationIndex - 1) * 10)
                actualPopulationIndex = 1;
            ViewBag.PopulationIndex = actualPopulationIndex;
            return View("AllCountries", country);
        }

        /*public ActionResult ReadData(FormCollection data, int countryIndex)
        {
            Person person = new Person();
            Country country = db.Countries.ToList()[countryIndex];

            try
            {
                person.id = db.People.ToList().Count() + Country.TemporalPeople.Count();
                person.firstName = data["newPersonName"];
                person.lastName = data["newPersonLastName"];
                person.birthdate = Convert.ToDateTime(data["newPersonBirthdate"]);
                person.email = person.firstName + person.lastName + "@hotmail.com";
                person.birthCountry = country.id;
                person.residenceCountry = country.id;

                ViewBag.ActualIndex = countryIndex;
                country.AddTemporal(person);
            }
            catch (FormatException)
            {

            }
            ViewBag.PopulationIndex = 1;
            return View("AllCountries", country);
        }*/

        [HttpPost] public string AddPerson([Bind(Include = "id,idNumber,firstName,lastName,birthdate")] Person person) // string PersonName, string PersonLastName, string Birthdate, int countryIndex
        {
            return person.firstName + "  " + person.lastName;
        }

        /*[HttpPost] public ActionResult DeleteTemporalPeople()
        {
            ViewBag.ActualIndex = 0;
            ViewBag.PopulationIndex = 1;
            Country.TemporalPeople = new List<Person>();
            return View("AllCountries", db.Countries.First());
        }*/

        /*[HttpPost] public ActionResult InsertTemporalPeople()
        {
            Country country;

            foreach (Person person in Country.TemporalPeople)
                db.People.Add(person);

            db.SaveChanges();

            Country.TemporalPeople = new List<Person>();
            ViewBag.ActualIndex = 0;
            ViewBag.PopulationIndex = 1;
            country = db.Countries.First();
            return View("AllCountries", country);
        }*/

        [HttpPost] public ActionResult AddFlag(Country country, HttpPostedFileBase flag1, int countryIndex)
        {
            Country countryModel = db.Countries.ToList()[countryIndex];
            try
            {
                HttpPostedFileBase file = Request.Files[0];
                countryModel.flag = new byte[file.ContentLength];
                file.InputStream.Read(countryModel.flag, 0, (int)file.ContentLength);
                db.SaveChanges();
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.ActualIndex = countryIndex;
            ViewBag.PopulationIndex = 1;
            return View("AllCountries", countryModel);
        }

        [HttpPost] public ActionResult AddAnthem(Country country, HttpPostedFileBase anthem1, int countryIndex)
        {
            Country countryModel = db.Countries.ToList()[countryIndex];
            try
            {
                HttpPostedFileBase file = Request.Files[0];
                countryModel.anthem = new byte[file.ContentLength];
                file.InputStream.Read(countryModel.anthem, 0, (int)file.ContentLength);
                db.SaveChanges();
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.ActualIndex = countryIndex;
            ViewBag.PopulationIndex = 1;
            return View("AllCountries", countryModel);
        }

        [HttpPost] public ActionResult Data(short sum)
        {
            System.Diagnostics.Debug.WriteLine("HERE");
            System.Diagnostics.Debug.WriteLine(ActualIndex + ":" + PopulationIndex);
            int actualCountry = ActualIndex;
            int actualPopulation = PopulationIndex;
            

            List<Country> countries = db.Countries.Include(c => c.Person).ToList();
            Country country;
            int actualPopulationIndex;

            ActualIndex = actualCountry;
            country = countries[actualCountry];

            actualPopulationIndex = actualPopulation + sum;

            if (actualPopulationIndex == 0)
                actualPopulationIndex = country.People1.Count() / 10 + 1;

            if (country.People1.Count() < (actualPopulationIndex - 1) * 10)
                actualPopulationIndex = 1;
            PopulationIndex = actualPopulationIndex;

            country.SelectedPeople = new List<Person>();
            int start = (PopulationIndex - 1) * 10;
            int end = (PopulationIndex) * 10;
            for (int i = start; i < end && i < country.People1.Count; i++)
            {
                country.SelectedPeople.Add(country.People1.ToList()[i]);
            }

            System.Diagnostics.Debug.WriteLine("OUT");
            System.Diagnostics.Debug.WriteLine(ActualIndex + ":" + PopulationIndex);
            return View("PeopleList", country);
        }

    }
}