//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountriesApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.People = new HashSet<Person>();
            this.People1 = new HashSet<Person>();
        }
    
        public int id { get; set; }
        [Display(Name = "Nombre")] public string name { get; set; }
        public decimal area { get; set; }
        [Display(Name = "Poblacion")] public decimal population { get; set; }
        [Display(Name = "Bandera")] public byte[] flag { get; set; }
        [Display(Name = "Himno")] public byte[] anthem { get; set; }
        [Display(Name = "Presidente")] public Nullable<int> presidentID { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People1 { get; set; }
    }
}
