

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CountriesApp.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CountriesEntities : DbContext
{
    public CountriesEntities()
        : base("name=CountriesEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<Person> People { get; set; }

}

}

