
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CountriesApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Country
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Country()
    {

        this.People = new HashSet<Person>();

        this.People1 = new HashSet<Person>();

        this.SelectedPeople = new HashSet<Person>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public decimal area { get; set; }

    public short population { get; set; }

    public byte[] flag { get; set; }

    public byte[] anthem { get; set; }

    public Nullable<int> presidentID { get; set; }



    public virtual Person Person { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Person> People { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Person> People1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Person> SelectedPeople { get; set; }

}

}
