
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CountriesApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {

            this.Countries = new HashSet<Country>();
        }

        public int id { get; set; }
        public int idNumber { get; set; }
        [Display(Name = "Nombre")]public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> birthCountry { get; set; }
        public Nullable<int> residenceCountry { get; set; }
        public System.DateTime birthdate { get; set; }
        public string email { get; set; }
        public byte[] photo { get; set; }
        public byte[] interview { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Countries { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
    }
}